<<<<<<< Updated upstream
name: Code Quality

on:
  push:
    branches: [main, development, feature/**, bugfix/**, hotfix/**]
  pull_request:
    branches: [main, beta, development]
=======
name: Quality

on:
  push:
    branches: [main, master, development, dev, feature/**, bugfix/**, hotfix/**]
  pull_request:
    branches: [main, master, development, dev]
>>>>>>> Stashed changes

jobs:
  quality:
    uses: ConductionNL/.github/.github/workflows/quality.yml@main
    with:
      app-name: opencatalogi
      php-version: "8.3"
<<<<<<< Updated upstream
      enable-psalm: false
      enable-phpstan: false
      enable-phpmetrics: true
      enable-frontend: true
      enable-eslint: true
=======
      nextcloud-ref: stable32
      enable-psalm: true
      enable-phpstan: true
      enable-phpmetrics: true
      enable-frontend: true
      enable-eslint: true
      enable-phpunit: true
      enable-newman: true
      newman-collection-path: "docs/assets"
>>>>>>> Stashed changes
